# Generated by Django 3.2.12 on 2022-03-22 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_alter_currentround_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentround',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.round'),
        ),
    ]
