# Generated by Django 3.2.12 on 2022-03-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_alter_currentround_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='biddingPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
